### ISSUE TITLE
m_create causes compilation issues in Xcode 9.3

### ISSUE THREAD

**Issue by JoeSzymanski** [jmfieldman/Mortar#23]
In testing updating to Xcode 9.3, we discovered a subtle bug that is caused by applying the `MortarNSObjectCreatable` protocol to all NSObjects.

This protocol is helpful in creating and configuring objects, but creates a problem in that it makes the `init()` method of NSObject public, even in subclasses where it wasn't public previously. We've run into common cases where a basic object can no longer be initialized because the compiler can't figure out if the subclass's `init()` or NSObject's `init()` method should be used. A simple example of this is trying to initialize NSCache.

For this scenario, we've found that a better option is to add a method that happens after default initialization: http://khanlou.com/2016/06/configuration-in-swift/ This prevents any issues from occurring by making some methods visible that shouldn't be.

In the short term, the `MortarNSObjectCreatable` should probably only be applied to classes that Mortar owns by default, which would allow others to add the method to classes on an as-need basis, rather than break things in unexpected ways.

**Comment by jmfieldman** [comment]
Your issue is definitely valid, and I like the solution -- I wasn't aware that you could write protocols with default behaviors like that.  So if I read this correctly, we just put m_create its own protocol, and anyone who updates to a new version of Mortar will just include something like:

```
extension NSObject: MortarCreatable { }
```

I'll play around with this over the weekend and if it's working well I'll put out an update.

**Comment by JoeSzymanski** [comment]
I do think this is new behavior related to the ABI stability work in Swift. It looks like the protocol is now resolving explicitly to the class that conforms to the protocol, rather than managing the protocol integration dynamically (which probably makes sense in Swift, since classes don't handle method resolution dynamically anymore).

I think your solution is correct. It's a one line change to restore the functionality in other projects.
