### ISSUE TITLE
Crash when trying to layout UIVisualEffectView

### ISSUE THREAD

**Issue by maximkhatskevich** [jmfieldman/Mortar#25]
The reason is that Mortar tries to add "Ghost View" on it, but it's not allowed - the "contentView" subviews supposed to be used for all subviews.

**Comment by jmfieldman** [comment]
Hi @maximkhatskevich -- my guess is that you're using VFL w/ the UIVisualEffectView as either the leading or trailing view?

e.g. ```effectView |> something | something``` ?

Can you paste the line of code that is causing the problem?

**Comment by maximkhatskevich** [comment]
@jmfieldman that's correct, I used an "effectView" as leading & trailing view in a VFL expression. I already found a solution that I'm happy with - I've made the "effectView" a subview (instead of using it as parent view in VFL) and defined its layout using anchor properties. So ignore this, for now, I guess.
