### ISSUE TITLE
Ambiguous use of init

### ISSUE THREAD

**Issue by AdamBCo** [jmfieldman/Mortar#31]
Hi @jmfieldman,

As soon as I add `import Mortar` to a file, I start to notice errors occurring in files related to my project, but not related to Mortar. For example Ambiguous use of 'init()'. Have you heard of anything like this before? As soon as I remove the `import Mortar`, everything goes back to normal and I can successfully build my project.

I'm using XCode Version 12.3 (12C33), Mortar 1.7.0, and building for iOS 12.

**Comment by jfieldmanbird** [comment]
Looking!

**Comment by AdamBCo** [comment]
@jmfieldman This may help, but the classes that seem to have issues are all ones that inherit from UICollectionViewController. Does that help?

**Comment by jfieldmanbird** [comment]
my initial feeling is that this is some new incompatibility with `MortarCreatable`.

In `NSObject+Mortar.swift`, Mortar extends `NSObject` with that protocol (that requires an `init()` method).

If you are not using `m_create` then you can try locally just commenting out NSObject+Mortar.swift and rebuilding.

**Comment by jfieldmanbird** [comment]
or if you're using cocoapods can you try `pod 'Mortar/Core_NoCreatable'` (from the comments in the file)

**Comment by jfieldmanbird** [comment]
or MortarVFL_NoCreatable if you are using the VFL

**Comment by AdamBCo** [comment]
@jfieldmanbird I just installed `pod 'Mortar/Core_NoCreatable'` and no luck. Same error as before.

**Comment by jfieldmanbird** [comment]
Can you post a screenshot of the error in context so i can see what is triggering it?

**Comment by jfieldmanbird** [comment]
oh and also can you verify in the filesystem that NSObject+Mortar.swift is actually missing from the Pods install dir (just sanity checking)

**Comment by jfieldmanbird** [comment]
another question: for your subclasses that are causing issues, do they have init methods with all default parameters 
e.g. 
```
init(var1: Int = 0, var2: String? = nil) {
}
```

**Comment by AdamBCo** [comment]
@jfieldmanbird I can confirm that `NSObject+Mortar.swift` is missing from the filesystem.

Here are the errors:

<img width="1035" alt="Screen Shot 2021-01-04 at 11 41 18 AM" src="https://user-images.githubusercontent.com/4572275/103572782-c1e2f380-4e92-11eb-9555-1a57ab80c6ab.png">

<img width="404" alt="Screen Shot 2021-01-04 at 11 41 05 AM" src="https://user-images.githubusercontent.com/4572275/103572775-bf809980-4e92-11eb-8eed-fa958c61f977.png">

Here is the initializer I am using for my CollectionViewController, which subclasses UICollectionViewController. The classes having issues subclass CollectionViewController.

<img width="594" alt="Screen Shot 2021-01-04 at 11 41 49 AM" src="https://user-images.githubusercontent.com/4572275/103572867-e50da300-4e92-11eb-991c-70e3abb73d7c.png">

**Comment by jfieldmanbird** [comment]
what are the candidates?  you should be able to see in the actual build log what the two candidates are (ref: where it says "Found this candidate" twice)

**Comment by AdamBCo** [comment]
@jfieldmanbird The first "Found this candidate" for each error refers to the file name listed above. When I click the second one, Xcode doesn't navigate me anywhere and the inspector is empty. Odd XCode issue? 🤨

**Comment by jmfieldman** [comment]
If I had to take a wild guess, I wonder if Xcode isn't picking up the Mortar change.  Maybe clean and rebuild?  

btw, i often have issues navigating by clicking on those candidates.  I usually have to look in the build log itself

![image](https://user-images.githubusercontent.com/85181/103574853-87bf2500-4e85-11eb-902d-98e84f4c803c.png)

then in the build log you can actually expand the full details of those messages and it should say what the candidates are

**Comment by jmfieldman** [comment]
ohhh i also just realized that the init you posted does have default values.

you have this

```
init(layout: UICollectionViewFlowLayout = UICollectionViewFlowLayout()) {
...
```

I think this could be a general issue if the compiler can't decide to use this one, or the default NSObject.init().  My suggestion is to remove the default value from your init and do something like this:

```
init(layout: UICollectionViewFlowLayout?) {
  let resolvedLayout = layout ?? UICollectionViewFlowLayout()
  self.layout = resolvedLayout
  super.init(collectionViewLayout: resolvedLayout)
}
```

then just explicitly pass nil where you want to use the default

**Comment by jfieldmanbird** [comment]
I'm guessing this was resolved?
